language: c++
compiler:
     - gcc
before_script:
     - mkdir build
     - cd build
     - cmake ..
script: 
     - make demo_em
branches:
    only:
      - master
  notifications:
    recipients:
    email:
      on_success: change
      on_failure: always
  
