language: c++
sudo: required
compiler:
     - gcc
before_script:
     - sudo apt-get install libopenmpi-dev libhdf5-openmpi-dev  liblua5.2-dev libgtest-dev
     - mkdir build
     - cd build
     - cmake ..
script:
     - make demo_em
branches:
    only:
      - master
